### ISSUE TITLE
[GRAPHICAL GLITCH] Hybrid nodes' type is not consistent among teleop and auto.

### ISSUE THREAD

**Issue by GiggyMantis** [Teesh/fnc-recon-frontend#11]
## Expected Behavior
When you select a hybrid node as a cube or cone scored in either autonomous or teleop, it locks out the other one, and changes the icon from a circle to a triangle (cone) or square (cube) in _both_ teleop and auto.

## Current Behavior
The icon only changes in the mode that it was scored in.

## Steps to Reproduce
1. Select a hybrid node as either cone or cube scored in either auto or teleop.
2. Switch to the other mode.
3. Visual inconsistency occurs.

## Images
![image](https://github.com/Teesh/fnc-recon-frontend/assets/71663261/63328658-93f0-4ea1-9edb-7bd4d71fca28)
![image](https://github.com/Teesh/fnc-recon-frontend/assets/71663261/f6eb5346-649f-45a2-a086-0ea180a922ea)
![image](https://github.com/Teesh/fnc-recon-frontend/assets/71663261/8d20f5ec-3447-41ac-961d-2adc54832a37)
![image](https://github.com/Teesh/fnc-recon-frontend/assets/71663261/7683ac9f-fa2e-43ff-a5f1-5c2d9fca173d)

## Disclaimer
This is a minor graphical bug and is not a high priority.

**Comment by GiggyMantis** [comment]
Confirmed solved by #14

**Comment by Teesh** [comment]
Fixed in [763bba3](https://github.com/Teesh/fnc-recon-frontend/commit/763bba351f71db58d168192bfebbb8d90f8a7429)
