### ISSUE TITLE
[BUG] Match number allows E, e, and decimals.

### ISSUE THREAD

**Issue by GiggyMantis** [Teesh/fnc-recon-frontend#12]
The default HTML number field allows capital and lowercase e, as well as decimals, to be input into the field. Consider changing to a proper integer field.

**Comment by GiggyMantis** [comment]
The mobile version has no response validation at all. (iOS 16.0.2, viewing through the in-discord safari browser)

**Comment by Teesh** [comment]
Fixed in [8238d8f](https://github.com/Teesh/fnc-recon-frontend/commit/8238d8fb3199415ddd749d77ffd3f23ceba83609)
