### ISSUE TITLE
[BUG] On Desktop, sometimes the first hybrid node you click becomes locked in both teleop and auto and appears with the cone icon.

### ISSUE THREAD

**Issue by GiggyMantis** [Teesh/fnc-recon-frontend#17]
![image](https://github.com/Teesh/fnc-recon-frontend/assets/71663261/92528588-5e35-41e4-8283-ae1d969c0f54)
![image](https://github.com/Teesh/fnc-recon-frontend/assets/71663261/6e94ee14-5012-4235-8e9b-3d8d9127a797)

As far as I can tell, it only happens when you've just loaded the page.

**Comment by GiggyMantis** [comment]
This only occurs if you click a hybrid node first.

**Comment by Teesh** [comment]
Fixed in [763bba3](https://github.com/Teesh/fnc-recon-frontend/commit/763bba351f71db58d168192bfebbb8d90f8a7429)
